# Generated by Django 4.2.7 on 2023-11-24 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('dest_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('src_port', models.PositiveIntegerField(default=0)),
                ('dest_port', models.PositiveIntegerField(default=0)),
                ('protocol', models.CharField(default='any', max_length=10)),
                ('action', models.CharField(default='deny', max_length=10)),
            ],
        ),
    ]
