# Generated by Django 4.2.7 on 2023-11-25 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FirewallLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('src_ip', models.GenericIPAddressField()),
                ('dest_ip', models.GenericIPAddressField()),
                ('src_port', models.PositiveIntegerField()),
                ('dest_port', models.PositiveIntegerField()),
                ('protocol', models.CharField(max_length=10)),
                ('action', models.CharField(max_length=10)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FirewallRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.PositiveIntegerField(default=0)),
                ('src_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('dest_ip', models.GenericIPAddressField(default='0.0.0.0')),
                ('src_port', models.IntegerField(default=-1)),
                ('dest_port', models.IntegerField(default=-1)),
                ('action', models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=5)),
                ('protocol', models.CharField(choices=[('tcp', 'Tcp'), ('udp', 'Udp'), ('any', 'Any')], default='any', max_length=3)),
            ],
        ),
    ]
