# Generated by Django 4.2.7 on 2023-11-25 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firewall_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firewallrule',
            name='action',
            field=models.CharField(choices=[('allow', 'Allow'), ('deny', 'Deny')], default='deny', max_length=5),
        ),
        migrations.AlterField(
            model_name='firewallrule',
            name='protocol',
            field=models.CharField(choices=[('tcp', 'Tcp'), ('udp', 'Udp'), ('any', 'Any')], default='any', max_length=3),
        ),
    ]
